# -*- coding: utf-8 -*-
"""Qwen Agent(AI).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8xF4RcMe91Knd4Hpat5AfWYv1vr4mO3
"""

# LlamaIndex for document indexing and retrieval
!pip install llama-index-core llama-index-embeddings-huggingface llama-index-readers-file

# LangChain and LangGraph
!pip install langchain langchain-community langgraph

# Whisper for speech-to-text
!pip install openai-whisper

# ffmpeg (required by Whisper to process audio files)
!sudo apt update && sudo apt install -y ffmpeg

# Transformers, quantization support, and audio utilities
!pip install transformers accelerate bitsandbytes
!pip install gtts pydub soundfile

import os
import json
import torch
import whisper
import soundfile as sf
from base64 import b64decode

from gtts import gTTS
from IPython.display import Audio, display, Javascript
from google.colab import output

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

from llama_index.core import (
    Settings,
    VectorStoreIndex,
    SimpleDirectoryReader,
    StorageContext,
    load_index_from_storage
)
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

"""# Load Models

"""

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# 4-bit quantization config to fit both models on a T4 GPU
bnb_config = BitsAndBytesConfig(load_in_4bit=True)

# Interviewer model
print("\nLoading Qwen (Interviewer)...")
interviewer_name = "Qwen/Qwen2.5-7B-Instruct"
interviewer_tokenizer = AutoTokenizer.from_pretrained(interviewer_name)
interviewer_model = AutoModelForCausalLM.from_pretrained(
    interviewer_name,
    device_map="auto",
    quantization_config=bnb_config,
    torch_dtype=torch.float16
)
print("Qwen loaded.")


# Evaluator model
print("\nLoading Mistral (Evaluator)...")
evaluator_name = "mistralai/Mistral-7B-Instruct-v0.2"
evaluator_tokenizer = AutoTokenizer.from_pretrained(evaluator_name)
evaluator_model = AutoModelForCausalLM.from_pretrained(
    evaluator_name,
    device_map="auto",
    quantization_config=bnb_config,
    torch_dtype=torch.float16
)
print("Mistral loaded.")


print("\nLoading Whisper...")
whisper_model = whisper.load_model("base")
print("Whisper loaded.")


Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
Settings.llm = None
print("Embedding model set.")

"""# Data Prep & Vector Index"""

folder_path = './data'
os.makedirs(folder_path, exist_ok=True)

# Job description for Entry level AI Engineer
jd_text = """
Job Title: Entry level AI Engineer

Responsibilities:
- Build and set up machine learning models for Natural Language Processing (NLP).
- Work with AI models like BERT and GPT to handle different tasks.
- Optimize models to ensure they respond quickly and efficiently.
- Collaborate with the team to integrate AI into real applications.

Requirements:
- Comfortable writing code in Python.
- Familiarity with AI tools like PyTorch or Hugging Face.
- Basic understanding of how computers process text (Arabic AI/AraBERT is a plus).
- Ability to write clean and organized code.
"""


file_path = os.path.join(folder_path, 'job_description.txt')
with open(file_path, 'w') as f:
    f.write(jd_text)
print(f"Job description saved to: {file_path}")

# Do not forget to add resume to the data folder after this cell

# Load all documents from the data folder and build a vector index
documents = SimpleDirectoryReader("./data").load_data()
index = VectorStoreIndex.from_documents(documents)

# Save the index to disk so it can be reloaded later if needed
index.storage_context.persist(persist_dir="./storage")
print(f"Indexed {len(documents)} document(s) and saved to ./storage")

"""# Audio Helpers"""

def record_audio(duration=120):
    """
    Records audio from the browser microphone.
    A 'Stop Recording' button appears in the output — click it when you are done speaking.
    - duration: maximum recording time in seconds as a safety fallback (default 120s)
    """
    print(f"\nLISTENING... Click the 'Stop Recording' button when you are done.")

    # The JS definition and the call are combined into one eval_js call
    # so that the record function is available in the same context
    RECORD_JS = f"""
    new Promise(async resolve => {{
      const stream = await navigator.mediaDevices.getUserMedia({{ audio: true }});
      const mediaRecorder = new MediaRecorder(stream);
      let chunks = [];

      mediaRecorder.ondataavailable = e => chunks.push(e.data);
      mediaRecorder.start();

      const btn = document.createElement('button');
      btn.textContent = 'Stop Recording';
      btn.style.cssText = `
        padding: 10px 24px;
        background-color: #c0392b;
        color: white;
        border: none;
        border-radius: 6px;
        font-size: 15px;
        cursor: pointer;
        margin-top: 8px;
      `;
      document.body.appendChild(btn);

      const timeout = setTimeout(() => mediaRecorder.stop(), {duration * 1000});

      btn.onclick = () => {{
        clearTimeout(timeout);
        mediaRecorder.stop();
        btn.disabled = true;
        btn.textContent = 'Recording stopped.';
      }};

      mediaRecorder.onstop = async () => {{
        const blob = new Blob(chunks);
        const reader = new FileReader();
        reader.readAsDataURL(blob);
        reader.onloadend = () => resolve(reader.result);
        stream.getTracks().forEach(track => track.stop());
        setTimeout(() => {{ if (btn.parentNode) btn.remove(); }}, 1500);
      }};
    }})
    """

    s = output.eval_js(RECORD_JS)
    b = b64decode(s.split(',')[1])
    filename = 'input_audio.wav'
    with open(filename, 'wb') as f:
        f.write(b)
    print("Audio captured.")
    return filename


def speak_text(text):
    """
    Converts text to speech using gTTS and plays it in the browser.
    Also prints the text so you can read along.
    """
    print(f"\nAI: {text}")
    tts = gTTS(text, lang='en')
    tts.save('response.mp3')
    display(Audio('response.mp3', autoplay=True))

"""# Interview Phase Logic"""

def update_interview_logic(state):
    """
    Controls the flow of the interview by updating the current phase
    and instruction based on the current step number.
    """
    step = state["current_step"]

    # Step 0: Welcome the candidate and set expectations
    if step == 0:
        state["current_phase"] = "Introduction and Objective Set"
        state["instruction"] = (
            "Greet the candidate professionally and explain that this is "
            "a structured behavioral assessment."
        )

    # Step 1: Test technical knowledge related to the job description
    elif step == 1:
        state["current_phase"] = "Phase I: Contextualized Job Knowledge"
        state["instruction"] = (
            "Ask one technical trade-off question based on the JD requirements."
        )

    # Steps 2 to 4: Behavioral questions using the STAR method
    elif 2 <= step <= 4:
        state["current_phase"] = "Phase II: The Behavioral Core"
        state["instruction"] = (
            "Ask a STAR-method question based on the resume. "
            "If the previous answer used 'We', ask what THEIR individual contribution was."
        )

    # Step 5: Test how the candidate responds to being corrected
    elif step == 5:
        state["current_phase"] = "Phase III: Cognitive Flexibility"
        state["instruction"] = (
            "Provide a gentle technical correction or alternative viewpoint "
            "to the candidate's last answer. Observe their receptiveness."
        )

    # Step 6: Close the interview politely
    elif step == 6:
        state["current_phase"] = "Phase IV: Closing"
        state["instruction"] = "Thank the candidate and ask if they have any questions for you."

    # Beyond step 6: Mark the interview as finished
    else:
        state["is_finished"] = True
        state["current_phase"] = "Evaluation Phase"
        state["instruction"] = "Generate the final scorecard based on the Horizontal Scoring rubric (1-5)."

    return state

"""# Generate Interviewer Responce (QWEN)"""

def generate_qwen_response(state):
    """
    Uses the Qwen model to generate the next interviewer question or statement
    based on the current phase, instruction, and conversation history.
    """

    prompt = f"""
You are an AI Technical Interviewer.
Current Phase: {state['current_phase']}
Protocol Instruction: {state['instruction']}
CRITICAL RULE: Keep response CONCISE (max 2 sentences).
Context: {state['context_data']}
History: {state['chat_history']}
"""
    messages = [
        {"role": "system", "content": "You are a structured professional interviewer."},
        {"role": "user", "content": prompt}
    ]

    # Apply the chat template expected by Qwen
    text = interviewer_tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    # Tokenize and move to GPU
    model_inputs = interviewer_tokenizer([text], return_tensors="pt").to(device)

    # Generate the response
    generated_ids = interviewer_model.generate(
        model_inputs.input_ids,
        attention_mask=model_inputs.attention_mask,
        max_new_tokens=150,
        do_sample=False,
        pad_token_id=interviewer_tokenizer.eos_token_id
    )

    # Decode only the newly generated tokens, excluding the input prompt
    input_length = model_inputs.input_ids.shape[1]
    response = interviewer_tokenizer.decode(
        generated_ids[0][input_length:],
        skip_special_tokens=True,
        clean_up_tokenization_spaces=True
    ).strip()

    return response

"""# Evaluate Candidate Answer (Mistral)"""

def evaluate_answer(question, answer, context):
    """
    Uses the Mistral model to evaluate the candidate's answer.
    Returns a dictionary with score (1-5), decision (PASS/FAIL), and a short reason.
    """

    evaluation_prompt = f"""
You are STRICTLY an evaluator. Do NOT roleplay. Do NOT continue the interview.

QUESTION:
{question}z

ANSWER:
{answer}

CONTEXT:
{context}

TASK:
1. Check if the answer is coherent and not gibberish.
2. Check if it directly addresses the question asked.
3. If the question is technical, check for accuracy.
4. If the question is behavioral, check if the answer tells a logical story.

Return ONLY valid JSON with no extra text:
{
  "score": 1-5,
  "decision": "PASS" or "FAIL",
  "reason": "max 15 words"
}
"""
    messages = [
        {"role": "system", "content": "You are a strict grading system."},
        {"role": "user", "content": evaluation_prompt}
    ]

    # Apply the chat template expected by Mistral
    text = evaluator_tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    # Tokenize and move to GPU
    model_inputs = evaluator_tokenizer([text], return_tensors="pt").to(device)

    # Generate the evaluation
    generated_ids = evaluator_model.generate(
        model_inputs.input_ids,
        attention_mask=model_inputs.attention_mask,
        max_new_tokens=500,
        do_sample=False,
        pad_token_id=evaluator_tokenizer.eos_token_id
    )

    # Decode only the newly generated tokens
    response_text = evaluator_tokenizer.decode(
        generated_ids[0][model_inputs.input_ids.shape[-1]:],
        skip_special_tokens=True
    ).strip()

    # Remove markdown code fences if the model wrapped the JSON in them
    response_text = response_text.replace("```json", "").replace("```", "").strip()

    # Parse the JSON response
    try:
        result = json.loads(response_text)
        if all(k in result for k in ["score", "decision", "reason"]):
            return result
        else:
            return {"score": 1, "decision": "FAIL", "reason": "Invalid response format"}
    except json.JSONDecodeError:
        # Fallback: check for PASS keyword in raw text if JSON parsing fails
        if "PASS" in response_text.upper():
            return {"score": 3, "decision": "PASS", "reason": "Parsed from raw output"}
        return {"score": 1, "decision": "FAIL", "reason": "Could not parse JSON"}

def handle_candidate_input(ai_question, user_text, interview_state, retry_count=0):
    """
    Gives Qwen the full context of the question and what the candidate said,
    and lets it freely decide what the candidate meant and what to do next.
    - retry_count tracks how many times this question has already been retried.
    - After a couple of retires, the question is automatically skipped regardless of the answer unless the candidate asked you to repeat the question or answered something relative to the question.
    - The candidate can ask you to answer a previous question that he skipped and now wants to answer
    """

    # If the question has already been retried once, force a skip
    if retry_count >= 2:
        return {
            "action": "proceed",
            "response": "That is alright. We will move on to the next question. "
                        "Please note that unanswered questions will be reflected in your final evaluation."
        }

    prompt = f"""
You are conducting a structured professional interview. The current question was:
"{ai_question}"

The candidate responded with:
"{user_text}"

Important rules:
- The candidate is allowed to skip any question if they choose to, or if they are unable to answer.
- If the candidate skips or cannot answer, acknowledge it professionally and let them know it will be noted in their evaluation.
- If the answer is a genuine attempt but incomplete or unclear, ask them to elaborate once.
- If the answer is a clear and relevant attempt, accept it and move forward.
- You may only ask the candidate to elaborate once. After that, move forward regardless.
- If the candidate asked a question answer it regardless.
- If the candidate asked to skip the question then skip it and move on.
- If the candidate asked you to re-ask a previous question, re-ask it and evaluate it, then continue.

Based on the above, decide:
1. What did the candidate mean or want?
2. What is the most appropriate and professional thing to say back?
3. Should the interview move forward or should the candidate be given one chance to elaborate?

Return ONLY valid JSON with no extra text:
{{
  "action": "proceed" or "retry",
  "response": "what you will say to the candidate"
}}
"""
    messages = [
        {"role": "system", "content": "You are an experienced professional interviewer."},
        {"role": "user", "content": prompt}
    ]

    text = interviewer_tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    model_inputs = interviewer_tokenizer([text], return_tensors="pt").to(device)

    generated_ids = interviewer_model.generate(
        model_inputs.input_ids,
        attention_mask=model_inputs.attention_mask,
        max_new_tokens=200,
        do_sample=False,
        pad_token_id=interviewer_tokenizer.eos_token_id
    )

    input_length = model_inputs.input_ids.shape[1]
    response_text = interviewer_tokenizer.decode(
        generated_ids[0][input_length:],
        skip_special_tokens=True
    ).strip()

    response_text = response_text.replace("```json", "").replace("```", "").strip()

    try:
        result = json.loads(response_text)
        if all(k in result for k in ["action", "response"]):
            return result
        else:
            return {"action": "proceed", "response": "Let us move on to the next question."}
    except:
        return {"action": "proceed", "response": "Let us move on to the next question."}

# Final score card
def generate_final_scorecard(interview_state):
    """
    Uses the Mistral model to generate a structured final evaluation report
    based on the full interview transcript after the interview is complete.
    Returns a dictionary with score, decision, reason, and a detailed report.
    """

    # Combine the full conversation into a single transcript string
    transcript = "\n".join(interview_state.get("chat_history", []))

    evaluation_prompt = f"""
You are an expert HR Psychometrician and Technical Evaluator.
Review the following interview transcript and provide a final report.

TRANSCRIPT:
{transcript}

EVALUATION CRITERIA:
1. Contextual Knowledge (30%): Depth of technical and professional logic.
2. Behavioral Evidence (40%): STAR method usage. Did they say 'I' or 'We'?
3. Conscientiousness: Methodical and proactive behavior.
4. Locus of Control: Did they take ownership or externalize blame?
5. Coachability: How did they react to correction in Phase III?

SCORING RUBRIC:
- 5 (Exceptional): Specific, quantifiable evidence with high ownership.
- 3 (Acceptable): General evidence, lacks proactive traits.
- 1 (Poor): Vague, hypothetical, or defensive answers.

Return ONLY valid JSON with no extra text:
{{
  "score": 1-5,
  "decision": "PASS" or "FAIL",
  "reason": "max 20 words",
  "detailed_report": "brief paragraph summarizing strengths and areas to improve"
}}
"""
    messages = [
        {"role": "system", "content": "You are a strict HR and Technical evaluator."},
        {"role": "user", "content": evaluation_prompt}
    ]

    # Apply the chat template expected by Mistral
    text = evaluator_tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    # Tokenize and move to GPU
    model_inputs = evaluator_tokenizer([text], return_tensors="pt").to(device)

    # Generate the final report (more tokens allowed for detailed output)
    generated_ids = evaluator_model.generate(
        model_inputs.input_ids,
        attention_mask=model_inputs.attention_mask,
        max_new_tokens=500,
        do_sample=False,
        pad_token_id=evaluator_tokenizer.eos_token_id
    )

    # Decode only the newly generated tokens
    response_text = evaluator_tokenizer.decode(
        generated_ids[0][model_inputs.input_ids.shape[-1]:],
        skip_special_tokens=True
    ).strip()

    # Remove markdown code fences if present
    response_text = response_text.replace("```json", "").replace("```", "").strip()

    # Parse the JSON response
    try:
        result = json.loads(response_text)
        if all(k in result for k in ["score", "decision", "reason", "detailed_report"]):
            return result
        else:
            return {"score": 1, "decision": "FAIL", "reason": "Invalid format", "detailed_report": response_text}
    except:
        return {"score": 1, "decision": "FAIL", "reason": "Could not parse JSON", "detailed_report": response_text}

"""# THE Interview"""

# Initialize the interview state with all required fields
interview_state = {
    "chat_history": [],       # stores the full conversation transcript
    "current_step": 0,        # tracks which phase/question we are on
    "current_phase": "Intro", # current phase name
    "candidate_answer": "",   # placeholder for the latest candidate answer
    "instruction": "",        # current instruction passed to Qwen
    "context_data": "Candidate is a CS student whith some entry knowledge in AI/NLP fields",
    "is_finished": False,     # flag to stop the loop when interview is done
    "scores": []              # will be filled by the final scorecard
}

print("=" * 50)
print("STARTING AUDIO INTERVIEW")
print("=" * 50)

try:
    while not interview_state["is_finished"]:

        # Step A: Update the phase and instruction based on current step
        interview_state = update_interview_logic(interview_state)
        if interview_state["is_finished"]:
            break

        print(f"\nCurrent Phase: {interview_state['current_phase']}")

        # Step B: Qwen generates and speaks the next question
        ai_question = generate_qwen_response(interview_state)
        speak_text(ai_question)

        # Step C: Record, transcribe, and validate the candidate's answer
        # Keeps looping until an acceptable response is captured
        valid_response = False
        retry_count=0

        while not valid_response:
            audio_file = record_audio(duration=120)
            print("Transcribing...")
            try:
                result = whisper_model.transcribe(audio_file)
                user_text = result["text"].strip()
                print(f"TRANSCRIPT: '{user_text}'")

                # Reject answers that are too short and re-ask immediately
                if len(user_text.split()) < 3:
                    speak_text(
                        "I apologize, I was unable to capture a full response. "
                        "Could you please answer the question again. \t\n" + ai_question
                    )
                    continue # Moved eval to end of interview (make it after each questin?)

                # Check if the answer is relevant to the question
                result = handle_candidate_input(ai_question, user_text, interview_state, retry_count)
                speak_text(result["response"])

                if result["action"] == "proceed":
                  valid_response = True
                else:
                  retry_count += 1

            except Exception as e:
                print(f"Transcription error: {e}")
                continue

        # Step D: Save the accepted answer and move to the next question
        interview_state["chat_history"].append(f"AI: {ai_question}")
        interview_state["chat_history"].append(f"Candidate: {user_text}")
        interview_state["current_step"] += 1
        print("Moving to next question...")

except KeyboardInterrupt:
    print("\nInterview paused by user.")

print("\nInterview session complete.")

"""# Score Card

"""

print("Generating Final Scorecard...")
print("=" * 50)

final_report = generate_final_scorecard(interview_state)

print(f"\nFINAL SCORE     : {final_report.get('score', 'N/A')} / 5")
print(f"DECISION        : {final_report.get('decision', 'N/A')}")
print(f"REASON          : {final_report.get('reason', 'N/A')}")
print(f"\nDETAILED REPORT :\n{final_report.get('detailed_report', 'N/A')}")
print("=" * 50)